### PR TITLE
Fix missing environment variables (specifically, precision)

### PR DESCRIPTION
**Pull request by bachya**
**Describe what the PR does:**

We were missing some environment variables in the mapping – this PR fixes things.

**Does this fix a specific issue?**

Fixes https://github.com/bachya/ecowitt2mqtt/issues/362

**Checklist:**

- [ ] Confirm that one or more new tests are written for the new functionality.
- [x] Run tests and ensure everything passes (with 100% test coverage).
- [ ] Update `README.md` with any new documentation.
- [ ] Add yourself to `AUTHORS.md`.

### CODE REVIEW

**Comment by bachya** [comment]
@alexdelprete Can you test the PR Docker image once it's [published](https://github.com/bachya/ecowitt2mqtt/actions/runs/3362620961/jobs/5574608188)?

**Comment by alexdelprete** [comment]
> @alexdelprete Can you test the PR Docker image once it's [published](https://github.com/bachya/ecowitt2mqtt/actions/runs/3362620961/jobs/5574608188)?

Sure, can you tell me how do I pull that specific version without waiting for a release tag? Never done it before. :)

**Comment by bachya** [comment]
> Sure, can you tell me how do I pull that specific version without waiting for a release tag? Never done it before. :)

Once that linked build is successful (will take a bit), you can pull `bachya/ecowitt2mqtt:pr-363`.

**Comment by alexdelprete** [comment]
> > Sure, can you tell me how do I pull that specific version without waiting for a release tag? Never done it before. :)
> 
> Once that linked build is successful (will take a bit), you can pull `bachya/ecowitt2mqtt:pr-363`.

so PRs have tags, one more thing I learned, thanks. will let you know about the test.

**Comment by bachya** [comment]
@alexdelprete I actually implemented PR-to-Docker-Hub based on your feedback (wanting to test a previous PR) – so, thank you for the push!

**Comment by alexdelprete** [comment]
@bachya it's not a default feature? Should be!! :)

Would it be integrated with ghcr.io? What advantages does DH offer vs GHCR?

**Comment by bachya** [comment]
> @bachya it's not a default feature? Should be!! :)
> 
> Would it be integrated with ghcr.io? What advantages does DH offer vs GHCR?

I've read several articles and can't seem to see an advantage of one over the other. I suppose ghcr.io benefits from being directly attached to the companion repo. Perhaps I should support both. 😉

**Comment by alexdelprete** [comment]
> > @bachya it's not a default feature? Should be!! :)
> > Would it be integrated with ghcr.io? What advantages does DH offer vs GHCR?
> 
> I've read several articles and can't seem to see an advantage of one over the other. I suppose ghcr.io benefits from being directly attached to the companion repo. Perhaps I should support both. 😉

You know that mine was a rethorical question...just a very indirect FR. 😜 

Actually, I do prefer much more ghcr.io: DH has strict pull limitations for free accounts, and using a lot of containers in my homelab, I did often hit the limit with checks etc. So whenever possible I opted for ghcr and other registries, and I always suggest devs to offer alternatives if it's not too difficult.

**Comment by bachya** [comment]
@alexdelprete Looks like the build has finished, FYI.

**Comment by alexdelprete** [comment]
> @alexdelprete Looks like the build has finished, FYI.

Working fine.

image
image

**Pull request merged**
