### PR TITLE
Add ability to disable calculated sensors

### PR DESCRIPTION
**Pull request by bachya**
**Describe what the PR does:**

https://github.com/bachya/ecowitt2mqtt/issues/220#issuecomment-1191470108 got me thinking: although Home Assistant users can disable calculated sensors (wind chill, heat index, etc.) in Home Assistant, non-Home Assistant users don't have the same ability. This PR introduces a new config option – `--disable-calculated-data` – that stops those values from being published to MQTT (regardless of whether the user is using Home Assistant MQTT Discovery).

**Does this fix a specific issue?**

N/A

**Checklist:**

- [x] Confirm that one or more new tests are written for the new functionality.
- [x] Run tests and ensure everything passes (with 100% test coverage).
- [x] Update `README.md` with any new documentation.
- [ ] Add yourself to `AUTHORS.md`.

### CODE REVIEW

**Comment by alexdelprete** [comment]
Just noticed that the env var is `ECOWITT2MQTT_DISABLED_CALCULATED_DATA`, should it be `ECOWITT2MQTT_DISABLE_CALCULATED_DATA` ?

**Comment by bachya** [comment]
@alexdelprete Good catch; thank you.

**Comment by alexdelprete** [comment]
Just noticed that the docs report `ECOWITT2MQTT_DISABLE_CALCULATE_DATA` (D missing in calculate). I didn't look at the code, hope it's just an error in the docs.

**Comment by bachya** [comment]
@alexdelprete Yep, just a docs issue. Good catch. Thank you!

**Pull request merged**
