### PR TITLE
Add ability to configure prefix for Home Assistant entity IDs

### PR DESCRIPTION
**Pull request by bachya**
**Describe what the PR does:**

This PR creates the option of an environment variable that, when set, is prefixed to Home Assistant entity IDs.

**Does this fix a specific issue?**

Fixes https://github.com/bachya/ecowitt2mqtt/issues/127
  
**Checklist:**

- [x] Update `README.md` with any new documentation.
- [ ] Add yourself to `AUTHORS.md`.

### CODE REVIEW

**Comment by alexdelprete** [comment]
Hi Aaron,

just tested this: the prefix is applied to the name instead of the entity id.

image

**Comment by bachya** [comment]
That's because you already have those entities created. Home Assistant won't automatically change entity IDs after their initial creation; you have to do that manually.

**Comment by alexdelprete** [comment]
I stopped ecowitt2mqtt and deleted the device from the MQTT integration, so all entities were removed, and I also deleted the old topics from MQTT just to make sure. Basically I wanted to start from scratch.

Then I restarted ecowitt2mqtt and now the entity ids have the configured prefix. :)

image

Would it be possible to have the prefix applied only to `Entity ID` and not the `Name` of the sensor?

image

**Comment by bachya** [comment]
The name is how the entity ID gets generated. I perused the MQTT Discovery docs and didn't see a way to manually set the entity ID; if you find a way, I'm happy to take a look.

**Pull request merged**
