### PR TITLE
feat: add ability to configure MQTT message and session expiry intervals

### PR DESCRIPTION
**Pull request by bachya**
**Describe what the PR does:**

Background: https://www.hivemq.com/blog/mqtt5-essentials-part4-session-and-message-expiry/

**Does this fix a specific issue?**

Fixes https://github.com/bachya/ecowitt2mqtt/issues/1024

**Checklist:**

- [x] Confirm that one or more new tests are written for the new functionality.
- [x] Run tests and ensure everything passes (with 100% test coverage).
- [x] Update `README.md` with any new documentation.

### CODE REVIEW

**Comment by jwillmer** [comment]
Is this code available as a docker container? Then I could test it on my setup.

**Comment by bachya** [comment]
> Is this code available as a docker container? Then I could test it on my setup.

https://github.com/bachya/ecowitt2mqtt/pkgs/container/ecowitt2mqtt/242520435?tag=pr-1037

**Comment by jwillmer** [comment]
it did not report me the message once i reconnected. but i need to check if all services are using the latest protocol. Would be good we get a second validation.

**Comment by jwillmer** [comment]
Today it crashed with this message. My broker supports MQTT5 and I did not modify my env variables since you use already good defaults.

```
2024-07-18 22:50:07,952 | ERROR | <class 'ValueError'> exception caused a shutdown: Properties only apply to MQTT V5
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/runtime.py", line 114, in create_loop
    async with Client(
  File "/venv/lib/python3.11/site-packages/aiomqtt/client.py", line 707, in __aenter__
    await loop.run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1431, in connect
    raise ValueError("Properties only apply to MQTT V5")
ValueError: Properties only apply to MQTT V5
```

**Comment by bachya** [comment]
> Today it crashed with this message. My broker supports MQTT5 and I did not modify my env variables since you use already good defaults.
> 
> 
> 
> ```
> 
> 2024-07-18 22:50:07,952 | ERROR | <class 'ValueError'> exception caused a shutdown: Properties only apply to MQTT V5
> 
> Traceback (most recent call last):
> 
>   File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/runtime.py", line 114, in create_loop
> 
>     async with Client(
> 
>   File "/venv/lib/python3.11/site-packages/aiomqtt/client.py", line 707, in __aenter__
> 
>     await loop.run_in_executor(
> 
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
> 
>     result = self.fn(*self.args, **self.kwargs)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1431, in connect
> 
>     raise ValueError("Properties only apply to MQTT V5")
> 
> ValueError: Properties only apply to MQTT V5
> 
> ```

Interesting. Perhaps I need to somehow specify the MQTT version when I create a client. I'll investigate.

**Comment by bachya** [comment]
Thanks for your patience, @jwillmer. I just pushed new code that allows you to change the version of the MQTT protocol inside `ecowitt2mqtt`'s MQTT client. Once the [build](https://github.com/bachya/ecowitt2mqtt/actions/runs/10222708891/job/28287837248?pr=1037) finishes, you can pull that same Docker image and try again. You'll use the `ECOWITT2MQTT_MQTT_PROTOCOL_VERSION` environment variable with a value of `5`.

**Comment by jwillmer** [comment]
That is my output. Sadly something is still broken? I use `eclipse-mosquitto:2` docker image and according to the ChatGPT it supports MQTT version 5 out of the box without any additional configuration.

```
2024-08-05 15:35:06,695 | INFO | Starting ecowitt2mqtt (version 2024.06.2)
2024-08-05 15:35:51,481 | ERROR | <class 'ValueError'> exception caused a shutdown: Properties only apply to MQTT V5
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/runtime.py", line 116, in create_loop
    async with Client(
  File "/venv/lib/python3.11/site-packages/aiomqtt/client.py", line 707, in __aenter__
    await loop.run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1431, in connect
    raise ValueError("Properties only apply to MQTT V5")
ValueError: Properties only apply to MQTT V5
```

**Comment by bachya** [comment]
Can I see your verbose-level output when you start `ecowitt2mqtt`? That message comes from the MQTT client, so I think there's something wrong here vs. with mosquitto.

**Pull request closed without merging**
