### PR TITLE
Ensure datetimes are converted before publishing to MQTT

### PR DESCRIPTION
**Pull request by bachya**
**Describe what the PR does:**

This PR fixes an issue with improperly casting a `datetime` prior to publishing to MQTT.

**Does this fix a specific issue?**

Fixes https://github.com/bachya/ecowitt2mqtt/issues/120
  
**Checklist:**

- [ ] Update `README.md` with any new documentation.
- [ ] Add yourself to `AUTHORS.md`.

### CODE REVIEW

**Comment by bachya** [comment]
@alexdelprete Please test this PR with your sensor.

**Comment by alexdelprete** [comment]
do I use the `dev` tag to pull this in my docker compose? Right now I'm using `latest`.

**Comment by bachya** [comment]
@alexdelprete This hasn't been published to Docker yet. Ideally, you could test by running the Python library itself. That said, if it would be easier, I can merge this, cut a new release, and if there are issues, come back?

**Comment by alexdelprete** [comment]
> @alexdelprete This hasn't been published to Docker yet. Ideally, you could test by running the Python library itself. That said, if it would be easier, I can merge this, cut a new release, and if there are issues, come back?

Sorry, I thought the dev tag was meant for testing etc. :)

I agree: merge it and I'll test the new release and report back.

**Comment by bachya** [comment]
The `dev` tag is, indeed, for testing, but it only gets built for merged PRs (because that puts functionality back in the `dev` branch). Building now; keep an eye here: https://github.com/bachya/ecowitt2mqtt/runs/6183500235?check_suite_focus=true

**Comment by alexdelprete** [comment]
I pulled the dev tag version just released, same issue:

```
DEBUG:ecowitt2mqtt:Using arguments: Namespace(log_level='DEBUG', mqtt_broker='mqtt.axel.dom', mqtt_port=1883, mqtt_username='mqtt_ha', mqtt_password='ha_mqtt', mqtt_topic='ecowitt2mqtt/GW2000A', hass_discovery=None, hass_discovery_prefix='homeassistant', endpoint='/data/report', port=8080, raw_data=None, input_unit_system='imperial', output_unit_system='metric')
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:ecowitt2mqtt:Received data from Ecowitt device: {'PASSKEY': 'YYYYYYYXXXXXXXYYYYYYYYYYYY', 'stationtype': 'GW2000A_V2.1.4', 'runtime': '963714', 'dateutc': '2022-04-26 21:36:30', 'tempinf': '73.8', 'humidityin': '55', 'baromrelin': '30.032', 'baromabsin': '29.672', 'tempf': '52.7', 'humidity': '82', 'winddir': '357', 'windspeedmph': '3.13', 'windgustmph': '4.03', 'maxdailygust': '16.55', 'solarradiation': '0.00', 'uv': '0', 'rainratein': '0.000', 'eventrainin': '0.000', 'hourlyrainin': '0.000', 'dailyrainin': '0.000', 'weeklyrainin': '0.000', 'monthlyrainin': '1.449', 'yearlyrainin': '4.622', 'rrain_piezo': '0.000', 'erain_piezo': '0.063', 'hrain_piezo': '0.000', 'drain_piezo': '0.063', 'wrain_piezo': '0.063', 'mrain_piezo': '2.984', 'yrain_piezo': '6.157', 'ws90cap_volt': '5.1', 'ws90_ver': '115', 'temp1f': '71.8', 'humidity1': '61', 'temp2f': '71.8', 'humidity2': '62', 'temp3f': '71.6', 'humidity3': '71', 'temp4f': '74.1', 'humidity4': '57', 'temp5f': '70.7', 'humidity5': '65', 'temp6f': '73.6', 'humidity6': '58', 'temp7f': '66.2', 'humidity7': '52', 'temp8f': '64.6', 'humidity8': '58', 'soilmoisture1': '55', 'soilmoisture2': '59', 'soilmoisture3': '62', 'soilmoisture4': '49', 'soilmoisture5': '50', 'pm25_ch1': '0.0', 'pm25_avg_24h_ch1': '0.0', 'tf_co2': '59.2', 'humi_co2': '65', 'pm25_co2': '11.1', 'pm25_24h_co2': '5.9', 'pm10_co2': '11.9', 'pm10_24h_co2': '6.4', 'co2': '540', 'co2_24h': '470', 'lightning_num': '203', 'lightning': '1', 'lightning_time': '1651008948', 'wh80batt': '3.28', 'batt1': '0', 'batt2': '0', 'batt3': '0', 'batt4': '0', 'batt5': '0', 'batt6': '0', 'batt7': '0', 'batt8': '0', 'soilbatt1': '1.3', 'soilbatt2': '1.3', 'soilbatt3': '1.2', 'soilbatt4': '1.3', 'soilbatt5': '1.3', 'pm25batt1': '3', 'wh57batt': '3', 'co2_batt': '6', 'wh90batt': '3.22', 'freq': '868M', 'model': 'GW2000A'}
DEBUG:ecowitt2mqtt:Wind Chill Temperature is only defined for temperatures at or below 50 F and wind speeds above 3 mph. (temperature: 52.7, wind speed: 3.13)
DEBUG:ecowitt2mqtt:Publishing entire device payload to single topic: ecowitt2mqtt/GW2000A
DEBUG:ecowitt2mqtt:Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b''
DEBUG:ecowitt2mqtt:Received CONNACK (0, 0)
DEBUG:ecowitt2mqtt:Sending DISCONNECT
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/src/ecowitt2mqtt/mqtt.py", line 116, in async_publish_payload
    await _async_publish_to_topic(client, data, topic)
  File "/usr/src/ecowitt2mqtt/mqtt.py", line 74, in _async_publish_to_topic
    await client.publish(topic, _generate_payload(data))
  File "/usr/src/ecowitt2mqtt/mqtt.py", line 22, in _generate_payload
    value = json.dumps(data)
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
INFO:aiohttp.access:10.1.10.160 [26/Apr/2022:21:36:30 +0000] "POST /data/report HTTP/1.1" 500 244 "-" "-"
```

**Comment by bachya** [comment]
That won't speed things up, unfortunately. How about pointing your device at a publicly-available version of ecowitt2mqtt that I spin up? That way, I can see the logs in real-time. If that works, email me at bachya1208@gmail.com and we'll coordinate.

**Comment by alexdelprete** [comment]
Dropped you an email...

**Pull request merged**
