### PR TITLE
add srain_piezo of WS90 for rain state detection

### PR DESCRIPTION
**Pull request by dkadioglu**
Adds rain state detection, which is available since GW2000 firmware 3.1.5

Fixes https://github.com/bachya/ecowitt2mqtt/issues/1102 

**Checklist:**

- [x] Confirm that one or more new tests are written for the new functionality.
- [x] Run tests and ensure everything passes (with 100% test coverage).
- [ ] Update `README.md` with any new documentation.

### CODE REVIEW

**Comment by dkadioglu** [comment]
What tests should I implement for srain_piezo to achieve successful checks?

**Comment by dkadioglu** [comment]
> > What tests should I implement for srain_piezo to achieve successful checks?
> 
> I would take a look at these tests as inspiration: [#1115 (comment)](https://github.com/bachya/ecowitt2mqtt/pull/1115#issuecomment-2381440313)

Thank you for giving me some hint. However, this link seems to be wrong.

**Comment by bachya** [comment]
> > > What tests should I implement for srain_piezo to achieve successful checks?
> > 
> > 
> > I would take a look at these tests as inspiration: [#1115 (comment)](https://github.com/bachya/ecowitt2mqtt/pull/1115#issuecomment-2381440313)
> 
> Thank you for giving me some hint. However, this link seems to be wrong.

Apologies! https://github.com/bachya/ecowitt2mqtt/blob/dev/tests/data/test_data_processing.py

**Comment by dkadioglu** [comment]
It took me some time familiarising with pytest and the CI pipeline. I hope, my implementation is appropriate. From my point of view, this should be ready to merge, please check.

**Review by bachya — APPROVED** [review]
Looks great! Thanks so much!

**Pull request merged**
